#pragma config(Sensor, dgtl1,  LED1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  LED2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  topButton,      sensorTouch)
#pragma config(Sensor, dgtl8,  trigger,        sensorTouch)
#pragma config(Sensor, dgtl9,  sideEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl11, frontEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           frontServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           sideServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

SensorValue[sideEncoder] = 0;
SensorValue[frontEncoder] = 0;
while (true){
	  motor[sideServo] += SensorValue[sideEncoder]*0.3;
    motor[frontServo] += SensorValue[frontEncoder]*0.3;
    wait1Msec(10);
		SensorValue[LED1] = SensorValue[topButton];
		SensorValue[LED2] = SensorValue[trigger];
};


}
